### ISSUE TITLE
Compute : Can't update an instance using the API

### ISSUE THREAD

**Issue by antoinebaudoux** [googleapis/java-compute#222]
I want to execute a very simple task and I'm stuck. I'm not sure if it is a bug of a misunderstanding from my part, but if it is a misunderstanding, it would help to clarify this in the doc.

I want to update the metadata of an Instance, and just the metadata.
First i retrieve a list of instances : 
```
val gcInstances = instanceClient.listInstances(projectZoneName).iterateAll().toList()
```
Which works fine.

Then I pick one of the Instance objects, and try to update its metadata  : 
```
val gcInstance = gcInstances[0]
val updateInstanceOperation = instanceClient.updateInstance(
                    "RESTART",
                    null,
                    ProjectZoneInstanceName.of(vmName, PROJECT_ID, ZONE),
                    gcInstance.toBuilder().setMetadata(newMetadata).build(),
                    null
                )
```

Whatever I put as the last parameter of the `updateInstance` method, I have an error.

If I put null : 
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.LinkedList.addAll(LinkedList.java:412)
	at java.base/java.util.LinkedList.addAll(LinkedList.java:391)
	at com.google.cloud.compute.v1.UpdateInstanceHttpRequest$Builder.addAllFieldMask(UpdateInstanceHttpRequest.java:386)
	at com.google.cloud.compute.v1.InstanceClient.updateInstance(InstanceClient.java:4143)
```

If I put an empty ArrayList : 
```
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource.machineType': ''. Machine type specified for the instance is not machine type.",
    "errors": [
      {
        "message": "Invalid value for field 'resource.machineType': ''. Machine type specified for the instance is not machine type.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

If I put just "metadata" : 
```
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource.name': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'",
    "errors": [
      {
        "message": "Invalid value for field 'resource.name': ''. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

Then I started adding field names to the field mask one by one until I got no errors, but then fields NOT in the mask get DELETED on the server when the call finally works. Which is bad, because from what I understand only fields in the field mask should be updated.

Am I missing something obvious here? 
Thanks in advance for your help

**Comment by athakor** [comment]
@antoinebaudoux  Updates an instance only if the necessary resources are available. This method can update only a specific set of instance properties. See Updating a running instance for a list of [updatable instance properties](https://cloud.google.com/compute/docs/instances/update-instance-properties#updatable-properties).

**Properties that require RESTART to update:**

- `reservation_affinity`
- `disk `- Boot disks
- `display_device`
- `guest_accelerator`
- `machine_type`
- `min_cpu_platform`
- `scheduling`
- `service_account`
- `shielded_instance_config`

**Properties that require only REFRESH to update:**

- `deletion_protection`
- `description`
- `disk `- Non-boot disks
- `labels`
- `metadata`
- `tags`

It would be great if you follow steps define in Api doc to [Update your instance](https://cloud.google.com/compute/docs/instances/update-instance-properties#update) like below way:

```javascript
import com.google.cloud.ServiceOptions;
import com.google.cloud.compute.v1.AttachedDisk;
import com.google.cloud.compute.v1.AttachedDiskInitializeParams;
import com.google.cloud.compute.v1.Instance;
import com.google.cloud.compute.v1.InstanceClient;
import com.google.cloud.compute.v1.Metadata;
import com.google.cloud.compute.v1.NetworkInterface;
import com.google.cloud.compute.v1.Operation;
import com.google.cloud.compute.v1.ProjectZoneInstanceName;
import com.google.cloud.compute.v1.ProjectZoneMachineTypeName;
import com.google.cloud.compute.v1.ProjectZoneName;
import com.google.cloud.compute.v1.UpdateInstanceHttpRequest;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

public class ComputeInstanceExample {
  protected static final String DEFAULT_PROJECT = ServiceOptions.getDefaultProjectId();
  private static final String DEFAULT_IMAGE =
      "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20150710";
  protected static final String ZONE = "us-central1-a";
  private static final String INSTANCE = "instance-2020-06";
  private static final String FORMATTED_INSTANCE =
      ProjectZoneInstanceName.format(INSTANCE, DEFAULT_PROJECT, ZONE);
  private static final String MACHINE_TYPE =
      ProjectZoneMachineTypeName.of("n1-standard-1", DEFAULT_PROJECT, ZONE).toString();

  public static void main(String[] args) throws IOException {
    try (InstanceClient client = InstanceClient.create()) {
      //createInstance(client);

      Instance remoteInstance = getInstance(client);
      System.out.println("Before Updating : " + remoteInstance);

      updateInstance(client, remoteInstance);
      System.out.println("After Updating : " + getInstance(client));
    }
  }

  /** Creates an Instance resource. */
  private static Operation createInstance(InstanceClient client) {
    ProjectZoneName zone = ProjectZoneName.of(DEFAULT_PROJECT, ZONE);
    AttachedDisk disk =
        AttachedDisk.newBuilder()
            .setBoot(true)
            .setAutoDelete(true)
            .setType("PERSISTENT")
            .setInitializeParams(
                AttachedDiskInitializeParams.newBuilder().setSourceImage(DEFAULT_IMAGE).build())
            .build();
    NetworkInterface networkInterface = NetworkInterface.newBuilder().setName("default").build();
    Instance instanceResource =
        Instance.newBuilder()
            .setName(INSTANCE)
            .setMachineType(MACHINE_TYPE)
            .addDisks(disk)
            .addNetworkInterfaces(networkInterface)
            .build();
    return client.insertInstance(zone.toString(), instanceResource);
  }

  /** Returns the specified Instance resource. */
  private static Instance getInstance(InstanceClient client) {
    return client.getInstance(FORMATTED_INSTANCE);
  }

  /** Updates an Instance resource. */
  private static Operation updateInstance(InstanceClient client, Instance instance) {
    List<String> requiredProperties =
        Arrays.asList("name", "machineType", "disks", "networkInterfaces");
    List<String> updatableProperties = Arrays.asList("metadata", "fingerprint", "description");
    List<String> fieldMask =
        Arrays.asList(
            requiredProperties.get(0),
            requiredProperties.get(1),
            requiredProperties.get(2),
            requiredProperties.get(3),
            updatableProperties.get(0),
            updatableProperties.get(1),
            updatableProperties.get(2));

    UpdateInstanceHttpRequest request =
        UpdateInstanceHttpRequest.newBuilder()
            .setMostDisruptiveAllowedAction("REFRESH")
            .setMinimalAction(null)
            .setInstance(FORMATTED_INSTANCE)
            .setInstanceResource(
                instance
                    .toBuilder()
                    .setDescription("updated description")
                    .setFingerprint(instance.getFingerprint())
                    .setMetadata(Metadata.getDefaultInstance())
                    .build())
            .addAllFieldMask(fieldMask)
            .build();
    return client.updateInstance(request);
  }
}
```

**Output:**
```
Before Updating : Instance{canIpForward=null, cpuPlatform=Intel Haswell, creationTimestamp=2020-10-05T22:42:05.757-07:00, deletionProtection=false, description=null, disks=[AttachedDisk{autoDelete=true, boot=true, deviceName=persistent-disk-0, diskEncryptionKey=null, diskSizeGb=10, guestOsFeatures=null, index=0, initializeParams=null, interface2=SCSI, kind=compute#attachedDisk, licenses=null, mode=READ_WRITE, shieldedInstanceInitialState=null, source=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/disks/instance-2020-06, type=PERSISTENT}], displayDevice=null, fingerprint=l08c6wVfFYU=, guestAccelerators=null, hostname=null, id=574772316938026307, kind=compute#instance, labelFingerprint=42WmSpB8rSM=, labels=null, machineType=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/machineTypes/n1-standard-1, metadata=Metadata{fingerprint=cwj02pw44AU=, items=null, kind=compute#metadata}, minCpuPlatform=null, name=instance-2020-06, networkInterfaces=[NetworkInterface{accessConfigs=null, aliasIpRanges=null, fingerprint=j79QoMAN2_I=, ipv6Address=null, kind=compute#networkInterface, name=nic0, network=https://www.googleapis.com/compute/v1/projects/project-name/global/networks/default, networkIP=10.128.0.8, subnetwork=https://www.googleapis.com/compute/v1/projects/project-name/regions/us-central1/subnetworks/default}], privateIpv6GoogleAccess=null, reservationAffinity=null, resourcePolicies=null, scheduling=Scheduling{automaticRestart=true, minNodeCpus=null, nodeAffinities=null, onHostMaintenance=MIGRATE, preemptible=false}, selfLink=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/instances/instance-2020-06, serviceAccounts=null, shieldedInstanceConfig=null, shieldedInstanceIntegrityPolicy=null, startRestricted=false, status=RUNNING, statusMessage=null, tags=Tags{fingerprint=42WmSpB8rSM=, items=null}, zone=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a}
After Updating : Instance{canIpForward=null, cpuPlatform=Intel Haswell, creationTimestamp=2020-10-05T22:42:05.757-07:00, deletionProtection=false, description=updated description, disks=[AttachedDisk{autoDelete=true, boot=true, deviceName=persistent-disk-0, diskEncryptionKey=null, diskSizeGb=10, guestOsFeatures=null, index=0, initializeParams=null, interface2=SCSI, kind=compute#attachedDisk, licenses=null, mode=READ_WRITE, shieldedInstanceInitialState=null, source=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/disks/instance-2020-06, type=PERSISTENT}], displayDevice=null, fingerprint=50pvQqNoMI8=, guestAccelerators=null, hostname=null, id=574772316938026307, kind=compute#instance, labelFingerprint=42WmSpB8rSM=, labels=null, machineType=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/machineTypes/n1-standard-1, metadata=Metadata{fingerprint=cwj02pw44AU=, items=null, kind=compute#metadata}, minCpuPlatform=null, name=instance-2020-06, networkInterfaces=[NetworkInterface{accessConfigs=null, aliasIpRanges=null, fingerprint=j79QoMAN2_I=, ipv6Address=null, kind=compute#networkInterface, name=nic0, network=https://www.googleapis.com/compute/v1/projects/project-name/global/networks/default, networkIP=10.128.0.8, subnetwork=https://www.googleapis.com/compute/v1/projects/project-name/regions/us-central1/subnetworks/default}], privateIpv6GoogleAccess=null, reservationAffinity=null, resourcePolicies=null, scheduling=Scheduling{automaticRestart=true, minNodeCpus=null, nodeAffinities=null, onHostMaintenance=MIGRATE, preemptible=false}, selfLink=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a/instances/instance-2020-06, serviceAccounts=null, shieldedInstanceConfig=null, shieldedInstanceIntegrityPolicy=null, startRestricted=false, status=RUNNING, statusMessage=null, tags=Tags{fingerprint=42WmSpB8rSM=, items=null}, zone=https://www.googleapis.com/compute/v1/projects/project-name/zones/us-central1-a}
```

**Comment by antoinebaudoux** [comment]
Thank you, I was not aware of this doc.

I will try the suggested method

**Comment by antoinebaudoux** [comment]
Hello, 

I'm trying to use the method you recommended : 

```
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{
  "error": {
    "code": 400,
    "message": "Invalid value for field 'resource.shieldedInstanceIntegrityPolicy': ''. Updating 'shieldedInstanceIntegrityPolicy' is not supported.",
    "errors": [
      {
        "message": "Invalid value for field 'resource.shieldedInstanceIntegrityPolicy': ''. Updating 'shieldedInstanceIntegrityPolicy' is not supported.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

But shieldedInstanceIntegrityPolicy is not in fieldMask. Can you advise please?

**Comment by antoinebaudoux** [comment]
If I put the entire field list as field mask, it works : 
```
                    val fieldMask = listOf(
                        "canIpForward",
                        "cpuPlatform",
                        "creationTimestamp",
                        "deletionProtection",
                        "description",
                        "disks",
                        "displayDevice",
                        "fingerprint",
                        "guestAccelerators",
                        "hostname",
                        "id",
                        "kind",
                        "labelFingerprint",
                        "labels",
                        "machineType",
                        "metadata",
                        "minCpuPlatform",
                        "name",
                        "networkInterfaces",
                        "reservationAffinity",
                        "resourcePolicies",
                        "scheduling",
                        "selfLink",
                        "serviceAccounts",
                        "shieldedInstanceConfig",
                        "shieldedInstanceIntegrityPolicy",
                        "startRestricted",
                        "status",
                        "statusMessage",
                        "tags",
                        "zone"
                    )
```

**Comment by antoinebaudoux** [comment]
Is it normal?

**Comment by athakor** [comment]
> Hello,
> 
> I'm trying to use the method you recommended :
> 
> ```
> Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
> {
>   "error": {
>     "code": 400,
>     "message": "Invalid value for field 'resource.shieldedInstanceIntegrityPolicy': ''. Updating 'shieldedInstanceIntegrityPolicy' is not supported.",
>     "errors": [
>       {
>         "message": "Invalid value for field 'resource.shieldedInstanceIntegrityPolicy': ''. Updating 'shieldedInstanceIntegrityPolicy' is not supported.",
>         "domain": "global",
>         "reason": "invalid"
>       }
>     ]
>   }
> }
> ```
> 
> But shieldedInstanceIntegrityPolicy is not in fieldMask. Can you advise please?

if you are trying to update `shieldedInstanceIntegrityPolicy` then these property must be present inside the `fieldMask`.

> Is it normal?

yes, That's how the current implementation works.

For your reference:

- https://cloud.google.com/compute/docs/instances/integrity-monitoring#updating-baseline
- https://cloud.google.com/compute/docs/instances/modifying-shielded-vm#api

**Comment by antoinebaudoux** [comment]
I don't want to update `shieldedInstanceIntegrityPolicy`. But if I don't put it in `fieldMask` I have the above mentioned error

**Comment by athakor** [comment]
@antoinebaudoux oh, you had specified the most disruptive action` "RESTART"` in your request and it required to have mandatory properties. Please check the Api doc to see [which properties is require for RESTART to update](https://cloud.google.com/compute/docs/instances/update-instance-properties#updatable-properties).

For your Info `shieldedInstanceIntegrityPolicy` is required propertis for disruptive action` "RESTART"`. so it's must be present inside the field mask otherwise compute engine returns an error.

**Comment by suztomo** [comment]
Closing for obsolete
