### ISSUE TITLE
[compute] insertAsync + get() over OperationFuture returns bad request for some projectIds

### ISSUE THREAD

**Issue by luciaems** [googleapis/java-compute#635]
#### Environment details

**1. Using bom-libraries**:
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>24.2.0</version>
  and compute:
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-compute</artifactId>
-> we use it shaded because possible dependency problems.
**2.  Os and java version:** 
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

#### Steps to reproduce

  1. try to insertAsync a VPC or firewall rule use .get() in order to wait for async task.

#### Code example

```java

 //from json downloaded from google cloud console all fields
 //in json "project_id": "abiquo.com:api-project-xxxxxxxxxxxx"
ServiceAccountCredentials serviceAccountCredentials = ServiceAccountCredentials.fromPkcs8(
                clientId, clientEmail, privateKeyFormatted, privateKeyId, Collections.emptySet())
                .toBuilder().setProjectId(projectId).build();

NetworksSettings networkSettings =
                    NetworksSettings.newBuilder().setCredentialsProvider(
                        FixedCredentialsProvider.create(serviceAccountCredentials)).build();
                networksClient = com.google.cloud.compute.v1.NetworksClient.create(networkSettings);
networksClient.insertAsync(projectId, networkToCreate).get();
```

#### Stack trace
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.NotFoundException: Not Found
	at abqshaded.gcp.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at abqshaded.gcp.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at abqshaded.gcp.com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:92)
	at abqshaded.gcp.com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:127)
	at com.abiquo.plugin.gcp.GCPGlobalNetwork.createGlobalNetwork(GCPGlobalNetwork.java:69)
	at com.abiquo.plugin.gcp.GCPPlugin.createGlobalNetwork(Unknown Source)
	at com.abiquo.plugin.gcp.GoogleLiveTest.testCreateGlobalNetwork(GoogleLiveTest.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: com.google.api.gax.rpc.NotFoundException: Not Found
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:85)
	at com.google.api.gax.httpjson.HttpJsonExceptionCallable$ExceptionTransformingFuture.onFailure(HttpJsonExceptionCallable.java:104)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at abqshaded.gcp.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at abqshaded.gcp.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at abqshaded.gcp.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277)
	at abqshaded.gcp.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at abqshaded.gcp.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:203)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
GET https://compute.googleapis.com:443/compute/v1/projects/abiquo.com/global/operations/operation-1644320589200-5d780389dbadc-07df3340-2712bd22
{
  "error": {
    "code": 404,
    "message": "The resource 'projects/abiquo.com' was not found",
    "errors": [
      {
        "message": "The resource 'projects/abiquo.com' was not found",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}

	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:190)
	... 6 more

```

#### External references 

 Trying to find the way to put project in the async request I read in:

- https://github.com/googleapis/java-compute/blob/main/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/NetworksClient.java#L525
- example in this repository https://github.com/googleapis/java-compute#example
- also the https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert where the path of project is the projecId

#### Any additional information below
- I have recently upgraded bom libraries, all methods were working with ProjectGlobalNetworkName (using projectId to build it) and I was using a custom wait for operations.
- project id from credentials .json is equal to projectName (if we perform a GET over ProjectsClient)
- I have tried this call ``` networksClient.insertAsync(projectId, networkToCreate).get();``` using: 
-- projectId(name) abiquo.com:api-project-xxxxxxxxxxxx
-- partial projectId : api-project-xxxxxxxxxxxx
-- project URL : https://www.googleapis.com/compute/v1/projects/abiquo.com:api-project-xxxxxxxxx
always the strings are cut or invalid (bad request)
**- If I perform the request without get, is properly performed.**

I am writing tests after upgrade, it seems is failing for firewalls(the two insertAsync I have tried at this point) also don't know if I am doing something wrong but I cannot find documentation to know if that is the case.

edited:
**Workaround** :  
```java
        InsertNetworkRequest request = InsertNetworkRequest.newBuilder()
            .setProject(projectId).setNetworkResource(networkToCreate).build();
        Operation op = networksClient.insertCallable().call(request);
        //+ custom wait until operation DONE
```

Please let me know if more information is needed.

looking forward for your reply,
Thanks!

**Comment by chanseokoh** [comment]
Can you clarify if everything was working fine and this started to happen after upgrading a bom for some libraries? Which bom and version?

**Comment by luciaems** [comment]
> Can you clarify if everything was working fine and this started to happen after upgrading a bom for some libraries? Which bom and version?

sure, I copy the info here from the original post:

com.google.cloud
libraries-bom
24.2.0

I came from alpha compute:
com.google.cloud
libraries-bom
5.3.0

"I have recently upgraded bom libraries, all methods were working with ProjectGlobalNetworkName (using projectId to build it) and I was using a custom wait for operations."

Also relevant:
If I perform the request without get, is properly performed.

**Comment by alicejli** [comment]
I've investigated this a bit and found the following:

1) I do not think it is an issue with the format of your projectId (I was able to replicate this issue with my projectId as well); rather, I think the error message is a little ambiguous.

```
{
  "error": {
    "code": 404,
    "message": "The resource 'projects/google.com' was not found",
    "errors": [
      {
        "message": "The resource 'projects/google.com' was not found",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}
```

I *think* what this actually means is the .get() method is not using the correct resource name. 
To your point, >`If I perform the request without get, is properly performed.` - I found that the request is performed even with the `get()` error, so I suspect it's something to do with the content of the `get()` call rather than the request itself.

I used the sample code:

```
public class ComputeExample {

    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException {
        final String project = "PROJECT-ID";
        final String region = "REGION";
        final String address = "test-address";

        AddressesClient addressesClient = AddressesClient.create();

//         AddressClient#insert()
        System.out.println("\n===============\nAddressClient#insert()\n===============");
        OperationFuture<Operation,Operation> insertResponse =
                addressesClient.insertAsync(project, region, Address.newBuilder().setName(address).build());
        Operation insertResponseOperation = insertResponse.get(); //I get the same 404 error if the `.get()` is set, but no error if it is not set

        // AddressClient#list()
        System.out.println("\n===============\nAddressClient#list()\n===============");
        for (Address addr : addressesClient.list(project, region).iterateAll()) {
            System.out.println(JsonFormat.printer().print(addr)); // Confirmed that addresses created via insert both with/without .get() are listed here
        }
    }
}
```

Sorry this doesn't really answer your original question, but just wanted to post my findings in case it's helpful for future investigations.

**Comment by lqiu96** [comment]
Taking a look (though probably late) and hopefully you've already solved this. 

> Also relevant:
> 
> * "If I perform the request without get, no exception is raised, and it is properly performed"
> * format of the projectId : "abiquo.com:api-project-xxxxxxxxxxxx"(maybe related)

My guess is that the projectId is incorrect. I believe if you follow: https://support.google.com/googleapi/answer/7014113?hl=en, your ID should just be `api-project-xxxxxxxxxxxx`. 

Testing locally with both my both projectId and projectNum, I've been able to call AddressesClient.insertAsync and all the subsequent calls (list, delete)

> - If I perform the request without get, is properly performed.

This part is throwing me off. I can't seem to replicate this at all. Without the get() call to block for the result, you *should* not be getting the created address listed from the list() call (mostly due to timing/ async).

Even checking manually afterwards (after the async call should be done creating), nothing shows up in my console. The subsequent delete() call fails as well -- since nothing was created. The only that works is that the app didn't throw an Exception.

pom.xml with libraries-bom v24.2.0
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>ComputeTest</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        <version>24.2.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-compute</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax</artifactId>
    </dependency>
  </dependencies>

</project>
```

I'll leave this open for a few days. Afterwards I'll close since there hasn't been any reply and no one else seems to have this issue.

**Comment by lqiu96** [comment]
Closing the issue. Feel free to re-open if this comes up again.
